import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import type { ClassifiedFile } from "../indexer/classify.js";
import type { RepoCommands, RepoIntelligence } from "./detect.js";

/**
 * repo.brain.md is the FIRST file an agent reads — a small bootloader, never the
 * whole repo. repo.map.json is its machine-readable twin. (PLAN claude A3,
 * Contract D.)
 */
export const REPO_BRAIN_FILENAME = "repo.brain.md";
export const REPO_MAP_FILENAME = "repo.map.json";

export interface TopDirectory {
  path: string;
  role: string;
  fileCount: number;
}

export interface RepoMap {
  version: 1;
  root: string;
  generatedAt: string;
  identity: string;
  fileCount: number;
  languages: string[];
  packageManagers: string[];
  commands: RepoCommands;
  entrypoints: string[];
  services: string[];
  envVars: string[];
  configFiles: string[];
  topDirectories: TopDirectory[];
  files: Array<{ path: string; role: string; importance: number; language: string | null }>;
}

const MAX_BRAIN_DIRS = 15;
const MAX_BRAIN_FILES = 12;
const MAX_BRAIN_ENV = 20;

function inferIdentity(root: string): string {
  try {
    const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
      description?: string;
      name?: string;
    };
    if (pkg.description) return pkg.description;
    if (pkg.name) return `${pkg.name} — see package.json`;
  } catch {
    /* fall through */
  }
  const py = safeRead(join(root, "pyproject.toml"));
  const desc = py && /description\s*=\s*["']([^"']+)["']/.exec(py)?.[1];
  if (desc) return desc;
  return `${basename(root)} repository`;
}

function safeRead(path: string): string | null {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return null;
  }
}

function topLevel(path: string): string {
  const idx = path.indexOf("/");
  return idx === -1 ? "." : path.slice(0, idx);
}

function buildTopDirectories(files: ClassifiedFile[]): TopDirectory[] {
  const byDir = new Map<string, { count: number; roles: Map<string, number> }>();
  for (const file of files) {
    const dir = topLevel(file.path);
    const entry = byDir.get(dir) ?? { count: 0, roles: new Map() };
    entry.count += 1;
    entry.roles.set(file.role, (entry.roles.get(file.role) ?? 0) + 1);
    byDir.set(dir, entry);
  }
  return [...byDir.entries()]
    .map(([path, { count, roles }]) => {
      const role = [...roles.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? "source";
      return { path, role, fileCount: count };
    })
    .sort((a, b) => b.fileCount - a.fileCount);
}

export function buildRepoMap(
  root: string,
  files: ClassifiedFile[],
  intel: RepoIntelligence,
  now: string,
): RepoMap {
  return {
    version: 1,
    root,
    generatedAt: now,
    identity: inferIdentity(root),
    fileCount: files.length,
    languages: intel.languages,
    packageManagers: intel.packageManagers,
    commands: intel.commands,
    entrypoints: intel.entrypoints,
    services: intel.services,
    envVars: intel.envVars,
    configFiles: intel.configFiles,
    topDirectories: buildTopDirectories(files),
    files: files
      .slice()
      .sort((a, b) => b.importance - a.importance)
      .map((f) => ({ path: f.path, role: f.role, importance: f.importance, language: f.language })),
  };
}

function commandsBlock(commands: RepoCommands): string[] {
  const rows: string[] = [];
  const push = (label: string, value?: string) => {
    if (value) rows.push(`- **${label}:** \`${value}\``);
  };
  push("Test", commands.test);
  push("Build", commands.build);
  push("Run", commands.run);
  push("Deploy", commands.deploy);
  return rows.length > 0 ? rows : ["- _No standard commands detected._"];
}

/** Render the small bootloader. Lists are capped to keep this well under ~6 KB. */
export function renderBrainMarkdown(map: RepoMap): string {
  const dirs = map.topDirectories.slice(0, MAX_BRAIN_DIRS);
  const keyFiles = map.files.filter((f) => f.role === "entrypoint" || f.importance >= 0.8).slice(0, MAX_BRAIN_FILES);
  const envShown = map.envVars.slice(0, MAX_BRAIN_ENV);

  const lines: string[] = [
    "# Repo Brain",
    "",
    "> Bootloader for coding agents. Read this first; do NOT read the whole tree.",
    "> Generated by `provena brain` — regenerate after large changes.",
    "",
    "## Identity",
    map.identity,
    "",
    "## Repo map",
  ];

  for (const dir of dirs) {
    lines.push(`- \`${dir.path}/\` — ${dir.role} (${dir.fileCount} files)`);
  }
  if (map.topDirectories.length > dirs.length) {
    lines.push(`- _…and ${map.topDirectories.length - dirs.length} more top-level entries._`);
  }

  lines.push("", "## Architecture");
  lines.push(`- Languages: ${map.languages.join(", ") || "unknown"}`);
  lines.push(`- Package managers: ${map.packageManagers.join(", ") || "none detected"}`);
  if (map.services.length > 0) {
    lines.push(`- Services (self-contained subprojects): ${map.services.join(", ")}`);
  }

  lines.push("", "## Entrypoints");
  if (map.entrypoints.length > 0) {
    for (const ep of map.entrypoints.slice(0, MAX_BRAIN_FILES)) lines.push(`- \`${ep}\``);
  } else {
    lines.push("- _None detected — see Key files below._");
  }

  lines.push("", "## Commands", ...commandsBlock(map.commands));

  if (keyFiles.length > 0) {
    lines.push("", "## Key files");
    for (const f of keyFiles) lines.push(`- \`${f.path}\` (${f.role})`);
  }

  if (envShown.length > 0) {
    lines.push("", "## Environment variables");
    lines.push(envShown.map((v) => `\`${v}\``).join(", ") + (map.envVars.length > envShown.length ? ", …" : ""));
  }

  lines.push(
    "",
    "## How to get more",
    "Do not scan the whole repo. Instead:",
    "- call the `provena` MCP tools (`get_context_pack`, `search_memory`), or",
    "- run `npx provena search \"<query>\"` for task-relevant, cited context.",
    "",
  );

  return lines.join("\n");
}

export interface WriteBrainResult {
  brainPath: string;
  mapPath: string;
  bytes: number;
}

export function writeBrain(provenaDir: string, map: RepoMap): WriteBrainResult {
  mkdirSync(provenaDir, { recursive: true });
  const brainPath = join(provenaDir, REPO_BRAIN_FILENAME);
  const mapPath = join(provenaDir, REPO_MAP_FILENAME);
  const markdown = renderBrainMarkdown(map);
  writeFileSync(brainPath, markdown, "utf8");
  writeFileSync(mapPath, `${JSON.stringify(map, null, 2)}\n`, "utf8");
  return { brainPath, mapPath, bytes: Buffer.byteLength(markdown, "utf8") };
}

export function brainExists(provenaDir: string): boolean {
  return existsSync(join(provenaDir, REPO_BRAIN_FILENAME));
}
