import { MEMORY_KINDS, MEMORY_SUBJECT_TYPES } from "./types.js";

export const MEMORY_EVENT_JSON_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "urn:provena:schema:memory-event:v1",
  title: "Provena memory event",
  description: "One immutable event in a repository's append-only memory ledger.",
  type: "object",
  additionalProperties: false,
  required: [
    "schema_version",
    "id",
    "kind",
    "subject_type",
    "title",
    "body",
    "structured_data",
    "status",
    "applies_to",
    "sources",
    "provenance",
    "authority",
    "confidence",
    "importance",
    "sensitivity",
    "created_at",
    "updated_at",
    "supersedes",
    "tags",
    "triggers",
  ],
  properties: {
    schema_version: { const: 1 },
    id: { type: "string", pattern: "^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$" },
    kind: { enum: MEMORY_KINDS },
    subject_type: { enum: MEMORY_SUBJECT_TYPES },
    title: { type: "string", minLength: 1, maxLength: 512 },
    body: { type: "string", minLength: 1, maxLength: 50000 },
    structured_data: { type: "object" },
    status: { enum: ["active", "superseded", "retracted"] },
    applies_to: {
      type: "array",
      maxItems: 256,
      items: {
        type: "string",
        minLength: 1,
        description: "Repository-relative POSIX path; absolute and parent-traversal paths are invalid.",
      },
      uniqueItems: true,
    },
    sources: {
      type: "array",
      maxItems: 256,
      items: {
        type: "object",
        additionalProperties: false,
        required: ["path"],
        properties: {
          path: {
            type: "string",
            minLength: 1,
            description: "Repository-relative POSIX path; absolute and parent-traversal paths are invalid.",
          },
          symbol: { type: "string", minLength: 1 },
          start_line: { type: "integer", minimum: 1 },
          end_line: { type: "integer", minimum: 1 },
          blob: { type: "string", minLength: 1 },
          commit: { type: "string", minLength: 1 },
        },
      },
    },
    provenance: {
      type: "object",
      additionalProperties: false,
      required: ["actor", "method"],
      properties: {
        actor: { type: "string", minLength: 1 },
        method: { enum: ["explicit", "observed", "imported"] },
        agent: { type: "string", minLength: 1 },
        session_id: { type: "string", minLength: 1 },
        command: { type: "string", minLength: 1 },
      },
    },
    authority: { enum: ["human", "agent", "tool", "system"] },
    confidence: { type: "number", minimum: 0, maximum: 1 },
    importance: { type: "number", minimum: 0, maximum: 1 },
    sensitivity: { enum: ["public", "internal", "confidential", "restricted"] },
    created_at: { type: "string", format: "date-time" },
    updated_at: { type: "string", format: "date-time" },
    supersedes: {
      type: "array",
      items: { type: "string", pattern: "^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$" },
      uniqueItems: true,
    },
    tags: {
      type: "array",
      items: { type: "string", minLength: 1 },
      uniqueItems: true,
    },
    triggers: {
      type: "array",
      items: { type: "string", minLength: 1 },
      uniqueItems: true,
    },
  },
} as const;
